version: "3.4"
services:
    workspace_flutter:
        build:
            context: .
            network: host
        volumes:
            - ../../..:/workspace
        command: sleep infinity